
package mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HealthCareInteropService", targetNamespace = "http://healthcareinterop.m2icone.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HealthCareInteropService {


    /**
     * 
     * @param integer1
     * @param operation
     * @param integer2
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculator", targetNamespace = "http://healthcareinterop.m2icone.org/", className = "mypackage.Calculator")
    @ResponseWrapper(localName = "calculatorResponse", targetNamespace = "http://healthcareinterop.m2icone.org/", className = "mypackage.CalculatorResponse")
    @Action(input = "http://healthcareinterop.m2icone.org/HealthCareInteropService/calculatorRequest", output = "http://healthcareinterop.m2icone.org/HealthCareInteropService/calculatorResponse")
    public String calculator(
        @WebParam(name = "operation", targetNamespace = "")
        String operation,
        @WebParam(name = "integer1", targetNamespace = "")
        int integer1,
        @WebParam(name = "integer2", targetNamespace = "")
        int integer2);

    /**
     * 
     * @param message
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "event", targetNamespace = "http://healthcareinterop.m2icone.org/", className = "mypackage.Event")
    @ResponseWrapper(localName = "eventResponse", targetNamespace = "http://healthcareinterop.m2icone.org/", className = "mypackage.EventResponse")
    @Action(input = "http://healthcareinterop.m2icone.org/HealthCareInteropService/eventRequest", output = "http://healthcareinterop.m2icone.org/HealthCareInteropService/eventResponse")
    public String event(
        @WebParam(name = "message", targetNamespace = "")
        String message);

}
